# Generated by Django 3.1.7 on 2021-06-19 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PAID', 'Đã thanh toán'), ('DEPOSITED', 'Đã đặt cọc'), ('UNPAID', 'Chưa thanh toán')], default='UNPAID', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_day', models.DateField()),
                ('start_time', models.TimeField(choices=[('06:00:00', '6h00'), ('09:00:00', '9h00'), ('18:00:00', '18h00')])),
                ('status', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='core.route')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('capacity', models.IntegerField(default=50)),
                ('place', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.IntegerField(choices=[(0, 'Seat 0'), (1, 'Seat 1'), (2, 'Seat 2'), (3, 'Seat 3'), (4, 'Seat 4'), (5, 'Seat 5'), (6, 'Seat 6'), (7, 'Seat 7'), (8, 'Seat 8'), (9, 'Seat 9'), (10, 'Seat 10'), (11, 'Seat 11'), (12, 'Seat 12'), (13, 'Seat 13'), (14, 'Seat 14'), (15, 'Seat 15'), (16, 'Seat 16'), (17, 'Seat 17'), (18, 'Seat 18'), (19, 'Seat 19'), (20, 'Seat 20'), (21, 'Seat 21'), (22, 'Seat 22'), (23, 'Seat 23'), (24, 'Seat 24'), (25, 'Seat 25'), (26, 'Seat 26'), (27, 'Seat 27'), (28, 'Seat 28'), (29, 'Seat 29'), (30, 'Seat 30')])),
                ('cost', models.IntegerField(choices=[(100000, 'Một trăm'), (200000, 'Hai trăm'), (300000, 'Ba trăm')], default=100000)),
                ('type', models.CharField(choices=[('N', 'Normal'), ('V', 'VIP')], default='N', max_length=1)),
                ('status', models.CharField(choices=[('T', 'Đã bán'), ('F', 'Chưa bán')], default='F', max_length=1)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.schedule')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trains', to='core.train'),
        ),
        migrations.AddField(
            model_name='route',
            name='departure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations_departure', to='core.station'),
        ),
        migrations.AddField(
            model_name='route',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations_destination', to='core.station'),
        ),
        migrations.CreateModel(
            name='BillDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='core.bill')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.ticket')),
            ],
        ),
    ]
