# Generated by Django 3.1.7 on 2021-06-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210618_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billdetail',
            name='status',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
